# Imports & Setup

In [25]:
import tomllib
from pathlib import Path
import polars as pl

In [26]:
config_file_path = Path("config.toml")

with config_file_path.open("rb") as config_file:
    config = tomllib.load(config_file)

COMPANIES = config['companies']

# Data Cleaning

In [27]:
companies = pl.read_parquet('ETL/data/raw/parquet/companies.parquet')
share_prices = pl.read_parquet('ETL/data/raw/parquet/share_prices.parquet')

In [28]:
with pl.Config(tbl_rows=25):
    plausible_companies = companies.drop_nulls(subset=pl.col('Number Employees')).sort('Number Employees', descending=True)
    selected_companies = plausible_companies.filter(pl.col('Company Name').is_in(COMPANIES))
    display(selected_companies)

shape: (1, 10)
┌──────────┬────────────┬────────────┬────────────┬───┬───────────┬────────┬───────────┬───────────┐
│ SimFinId ┆ Company    ┆ IndustryId ┆ ISIN       ┆ … ┆ Business  ┆ Market ┆ CIK       ┆ Main      │
│ ---      ┆ Name       ┆ ---        ┆ ---        ┆   ┆ Summary   ┆ ---    ┆ ---       ┆ Currency  │
│ i64      ┆ ---        ┆ f64        ┆ str        ┆   ┆ ---       ┆ str    ┆ f64       ┆ ---       │
│          ┆ str        ┆            ┆            ┆   ┆ str       ┆        ┆           ┆ str       │
╞══════════╪════════════╪════════════╪════════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 62747    ┆ AMAZON COM ┆ 103002.0   ┆ US02313510 ┆ … ┆ Amazon.co ┆ us     ┆ 1.018724e ┆ USD       │
│          ┆ INC        ┆            ┆ 67         ┆   ┆ m Inc is  ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ an online ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ re…       ┆        ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴───┴───────────┴────────┴───────────┴───────────┘

In [29]:
SIMFIN_IDS = [id for id in selected_companies['SimFinId']]

In [30]:
with pl.Config(tbl_rows=25):
    share_prices = share_prices.filter(pl.col('SimFinId').is_in(SIMFIN_IDS))
    display(share_prices)

shape: (1_238, 9)
┌──────────┬────────┬────────┬────────┬───┬────────────┬───────────┬──────────┬────────────────────┐
│ SimFinId ┆ Open   ┆ High   ┆ Low    ┆ … ┆ Adj. Close ┆ Volume    ┆ Dividend ┆ Shares Outstanding │
│ ---      ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---        ┆ ---       ┆ ---      ┆ ---                │
│ i64      ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64        ┆ i64       ┆ f64      ┆ f64                │
╞══════════╪════════╪════════╪════════╪═══╪════════════╪═══════════╪══════════╪════════════════════╡
│ 62747    ┆ 100.86 ┆ 101.79 ┆ 99.88  ┆ … ┆ 100.58     ┆ 102279660 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 101.05 ┆ 102.2  ┆ 100.56 ┆ … ┆ 102.15     ┆ 79546260  ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 102.22 ┆ 102.65 ┆ 100.88 ┆ … ┆ 102.14     ┆ 93112340  ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 102.0  ┆ 109.0  ┆ 101.9  ┆ … ┆ 108.44     ┆ 134334180 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 110.02 ┆ 114.6  ┆ 109.31 ┆ … ┆ 114.17     ┆ 161743860 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 112.88 ┆ 116.67 ┆ 112.25 ┆ … ┆ 115.38     ┆ 137331340 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 117.3  ┆ 123.05 ┆ 116.75 ┆ … ┆ 120.41     ┆ 240764020 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 118.62 ┆ 120.0  ┆ 115.8  ┆ … ┆ 118.75     ┆ 158600200 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 119.5  ┆ 122.25 ┆ 119.3  ┆ … ┆ 119.68     ┆ 115413880 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 120.83 ┆ 121.42 ┆ 113.98 ┆ … ┆ 116.41     ┆ 149533580 ┆ null     ┆ 9.9800e9           │
│ 62747    ┆ 118.45 ┆ 119.7  ┆ 117.55 ┆ … ┆ 118.17     ┆ 84365900  ┆ null     ┆ 9.9755e9           │
│ 62747    ┆ 120.0  ┆ 121.21 ┆ 119.1  ┆ … ┆ 119.97     ┆ 101331040 ┆ null     ┆ 9.9755e9           │
│ 62747    ┆ 120.85 ┆ 121.02 ┆ 119.1  ┆ … ┆ 120.51     ┆ 76635940  ┆ null     ┆ 9.9755e9           │
│ …        ┆ …      ┆ …      ┆ …      ┆ … ┆ …          ┆ …         ┆ …        ┆ …                  │
│ 62747    ┆ 217.45 ┆ 217.72 ┆ 212.42 ┆ … ┆ 212.71     ┆ 42387585  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 211.63 ┆ 213.34 ┆ 204.16 ┆ … ┆ 212.8      ┆ 58957977  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 214.94 ┆ 218.16 ┆ 213.09 ┆ … ┆ 214.35     ┆ 39120603  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 218.35 ┆ 219.97 ┆ 208.37 ┆ … ┆ 208.74     ┆ 40548571  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 208.65 ┆ 212.62 ┆ 206.99 ┆ … ┆ 212.28     ┆ 51771737  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 213.35 ┆ 214.01 ┆ 202.55 ┆ … ┆ 205.02     ┆ 42948447  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 200.11 ┆ 206.8  ┆ 197.43 ┆ … ┆ 203.8      ┆ 60853084  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 204.8  ┆ 209.98 ┆ 203.26 ┆ … ┆ 208.36     ┆ 38610085  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 204.4  ┆ 205.77 ┆ 198.3  ┆ … ┆ 200.7      ┆ 49863755  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 199.49 ┆ 202.27 ┆ 192.53 ┆ … ┆ 199.25     ┆ 59802821  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 195.6  ┆ 196.73 ┆ 190.85 ┆ … ┆ 194.54     ┆ 61829231  ┆ null     ┆ 1.0598e10          │
│ 62747    ┆ 193.9  ┆ 200.18 ┆ 193.4  ┆ … ┆ 196.59     ┆ 54002880  ┆ null     ┆ 1.0598e10          │
└──────────┴────────┴────────┴────────┴───┴────────────┴───────────┴──────────┴────────────────────┘

In [31]:
share_prices = share_prices.drop(pl.col('Dividend'), pl.col('SimFinId'))
share_prices

shape: (1_238, 7)
┌────────┬────────┬────────┬────────┬────────────┬───────────┬────────────────────┐
│ Open   ┆ High   ┆ Low    ┆ Close  ┆ Adj. Close ┆ Volume    ┆ Shares Outstanding │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---        ┆ ---       ┆ ---                │
│ f64    ┆ f64    ┆ f64    ┆ f64    ┆ f64        ┆ i64       ┆ f64                │
╞════════╪════════╪════════╪════════╪════════════╪═══════════╪════════════════════╡
│ 100.86 ┆ 101.79 ┆ 99.88  ┆ 100.58 ┆ 100.58     ┆ 102279660 ┆ 9.9800e9           │
│ 101.05 ┆ 102.2  ┆ 100.56 ┆ 102.15 ┆ 102.15     ┆ 79546260  ┆ 9.9800e9           │
│ 102.22 ┆ 102.65 ┆ 100.88 ┆ 102.14 ┆ 102.14     ┆ 93112340  ┆ 9.9800e9           │
│ 102.0  ┆ 109.0  ┆ 101.9  ┆ 108.44 ┆ 108.44     ┆ 134334180 ┆ 9.9800e9           │
│ 110.02 ┆ 114.6  ┆ 109.31 ┆ 114.17 ┆ 114.17     ┆ 161743860 ┆ 9.9800e9           │
│ …      ┆ …      ┆ …      ┆ …      ┆ …          ┆ …         ┆ …                  │
│ 204.8  ┆ 209.98 ┆ 203.26 ┆ 208.36 ┆ 208.36     ┆ 38610085  ┆ 1.0598e10          │
│ 204.4  ┆ 205.77 ┆ 198.3  ┆ 200.7  ┆ 200.7      ┆ 49863755  ┆ 1.0598e10          │
│ 199.49 ┆ 202.27 ┆ 192.53 ┆ 199.25 ┆ 199.25     ┆ 59802821  ┆ 1.0598e10          │
│ 195.6  ┆ 196.73 ┆ 190.85 ┆ 194.54 ┆ 194.54     ┆ 61829231  ┆ 1.0598e10          │
│ 193.9  ┆ 200.18 ┆ 193.4  ┆ 196.59 ┆ 196.59     ┆ 54002880  ┆ 1.0598e10          │
└────────┴────────┴────────┴────────┴────────────┴───────────┴────────────────────┘